name: Action CI

on:
  schedule:
    - cron: "0 6 * * *"
  push:
  pull_request:

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: Action CI
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python environment report
        run: python -c "import sys; print(sys.version)"
      - name: Action CI - default
        uses: f-actions/font-bakery@master
        with:
          subcmd: "--help"
      - name: Action CI - default with single file
        uses: f-actions/font-bakery@master
        with:
          subcmd: "check-profile"
          args: "tests/check-test.py"
          path: "tests/NotoSans-Regular.ttf"
      - name: Action CI - default with wildcard path
        uses: f-actions/font-bakery@master
        with:
          subcmd: "check-profile"
          args: "tests/check-test.py"
          path: "tests/*.ttf"
      - name: Action CI - fontbakery master branch version
        uses: f-actions/font-bakery@master
        with:
          subcmd: "check-profile"
          args: "tests/check-test.py"
          path: "tests/*.ttf"
          version: "master"
      - name: Action CI - fontbakery pinned release version
        uses: f-actions/font-bakery@master
        with:
          subcmd: "check-profile"
          args: "tests/check-test.py"
          path: "tests/*.ttf"
          version: "0.7.25"
